# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/v2.3.2/www/docs/static/schema.json

version: 2
project_name: ekdo
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.gitCommit={{.Commit}}
      - -X main.buildTime={{.Date}}
      - -X main.goVersion={{.Env.GO_VERSION}}
      - -X main.osArch={{.Arch}}
archives:
  - name_template: "{{ tolower .ProjectName }}-{{ tolower .Os }}-{{ tolower .Arch }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Branch }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  github:
    owner: mecha-hq
    name: ekdo
  name_template: "{{ .Tag }}"
  prerelease: auto
dockers:
  - image_templates:
      - "ghcr.io/mecha-hq/ekdo:{{ .Version }}-amd64"
    # use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
  - image_templates:
      - "ghcr.io/mecha-hq/ekdo:{{ .Version }}-arm64"
    # use: buildx
    goarch: arm64
    dockerfile: Dockerfile
    build_flag_templates:
      - "--target=goreleaser"
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
docker_manifests:
  - name_template: "ghcr.io/mecha-hq/ekdo:{{ .Version }}"
    image_templates:
      - "ghcr.io/mecha-hq/ekdo:{{ .Version }}-amd64"
      - "ghcr.io/mecha-hq/ekdo:{{ .Version }}-arm64"
