---
name: build

on:
  push:
    branches:
      - main

jobs:
  qa:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: TODO
        run: echo "TODO"

  build:
    needs: qa
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        arch: ["amd64", "arm64"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: docker build --platform=linux/${{ matrix.arch }} --tag ghcr.io/mecha-hq/ekdo:latest-${{ matrix.arch }} .
      - name: Push image
        run: docker push ghcr.io/mecha-hq/ekdo:latest-${{ matrix.arch }}

  finalize:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull images
        run: |
          docker pull ghcr.io/mecha-hq/ekdo:latest-amd64
          docker pull ghcr.io/mecha-hq/ekdo:latest-arm64
      - name: Create Docker manifest
        run: docker manifest create ghcr.io/mecha-hq/ekdo:latest ghcr.io/mecha-hq/ekdo:latest-amd64 ghcr.io/mecha-hq/ekdo:latest-arm64
      - name: Annotate Docker manifest
        run: |
          docker manifest annotate --arch amd64 --os linux ghcr.io/mecha-hq/ekdo:latest ghcr.io/mecha-hq/ekdo:latest-amd64
          docker manifest annotate --arch arm64 --os linux ghcr.io/mecha-hq/ekdo:latest ghcr.io/mecha-hq/ekdo:latest-arm64
